# Generated by Django 4.2.5 on 2023-09-13 06:50

from django.db import migrations, models
import django_enum.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='agreement',
            field=django_enum.fields.EnumCharField(choices=[('Материал не выбран', 'NOT_SELECTED'), ('Расширен без согласования', 'EXTENDED_WITHOUT_AGREEMENT'), ('Расширен после согласования', 'EXTENDED_AFTER_AGREEMENT'), ('Согласование не требуется', 'AGREEMENT_NOT_REQUIRED')], max_length=27, verbose_name='Согласование'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(verbose_name='Дата создания заявки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=django_enum.fields.EnumCharField(choices=[('В обработке (повторно)', 'IN_PROCESS_AGAIN'), ('В обработке (подтверждена)', 'IN_PROCESS_ACCEPTED'), ('Возвращена на уточнение', 'RETURNED_FOR_CLARIFICATION'), ('Обработка завершена', 'PROCESSED'), ('Отправлена в обработку', 'RETURNED_FOR_PROCESS'), ('Отправлена в обработку (повторно)', 'RETURNED_FOR_PROCESS_AGAIN')], max_length=33, verbose_name='Статус заявки'),
        ),
    ]
